export const employeeData = [
  {
    id: 1,
    firstname: "vinay",
    lastname: "chaurasiya",
    email: "23@gmail.com",
    salary: "3000",
    date: "21/12/12",
  },
  {
    id: 2,
    firstname: "Yash",
    lastname: "Dave",
    email: "daveya73@gmail.com",
    salary: "30100",
    date: "21/12/12",
  },
  {
    id: 3,
    firstname: "aditya",
    lastname: "desai",
    email: "desai@gmail.com",
    salary: "301100",
    date: "21/12/12",
  },
  {
    id: 4,
    firstname: "mukund",
    lastname: "dhanuka",
    email: "dhanuka7@gmail.com",
    salary: "300099",
    date: "21/12/12",
  },
  {
    id: 5,
    firstname: "krishi",
    lastname: "chaurasiya",
    email: "krishiasiya73@gmail.com",
    salary: "30001",
    date: "21/12/12",
  },
];
